@echo off
cd /d %~dp0

set DISCORD_BOT_TOKEN=MTA0MjQwNTgzODE1MDY5NzA0MA.GqIVVy.EfP7aye7uGZD4tptMZKK--DGmk26ngmB2yrUDg
set BCDICE_API_URL=https://bcdice.onlinesession.app
set IGNORE_ERROR=
REM set BCDICE_PASSWORD=TrickToTpass2
REM set BCDICE_API_SECONDARY=https://bcdice.kazagakure.net
REM set BCDICE_DEFAULT_SYSTEM=DiceBot
REM set BCDICE_MENTION_MODE=1
REM set BCDICE_RESULT_DISPLAY_FORMAT=V1
REM set BCDICE_SLASH_PREFIX=bcdice
REM set BCDICE_SLASH_SHORT_PREFIX=br
REM set BCDICE_STANDARD_INPUT_DISABLED=disabled
REM set BCDICE_SLASH_TABLE_SUGGESTION_DISABLED=disabled

java -jar discord-bcdicebot.jar %DISCORD_BOT_TOKEN% %BCDICE_API_URL% %IGNORE_ERROR%
pause
